#!/bin/bash

source /root/spark_files/configure_spark.sh

# TODO: move this to the configure script of some base directory
chmod a+rwx /tmp

env

echo "preparing Spark"
prepare_spark "master"

echo "adding test data to HDFS"
cp /root/spark_shell_files/test.txt /tmp
sudo -u hdfs hadoop dfsadmin -safemode wait
sudo -u hdfs hadoop fs -put /tmp/test.txt hdfs://master:9000/user/hdfs/test.txt

cp /root/spark_shell_files/test.spark /

echo "starting Spark Shell"
cd $SPARK_HOME
sudo -u hdfs HDFS_PREFIX=hdfs://master:9000 ./spark-shell
