# Shark master
FROM shark-base:0.9.0-SNAPSHOT
MAINTAINER amplab amp-docker@eecs.berkeley.edu

# Add run script
ADD files /root/shark_master_files

# Add default command for master
CMD ["/root/shark_master_files/default_cmd"]

